//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sa_POS_TrxHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sa_POS_TrxHeader()
        {
            this.sa_POS_TrxDetails = new HashSet<sa_POS_TrxDetails>();
        }
    
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
        public string TrxNo { get; set; }
        public string TrxType { get; set; }
        public string YearID { get; set; }
        public string PeriodID { get; set; }
        public Nullable<System.DateTime> TrxDate { get; set; }
        public string TrxStatus { get; set; }
        public string TrxDescA { get; set; }
        public string TrxDescE { get; set; }
        public string IntRefrence { get; set; }
        public Nullable<decimal> TrxAmount { get; set; }
        public Nullable<decimal> TrxBalance { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public string CustomerCode { get; set; }
        public string WarehouseCode { get; set; }
        public string SourceDocNo { get; set; }
        public string SourceDocType { get; set; }
        public Nullable<System.DateTime> TrxTime { get; set; }
        public string POSShift { get; set; }
        public string POSCode { get; set; }
        public string OperatorCode { get; set; }
        public string SourceDocYearId { get; set; }
        public string SourceDocPeriodId { get; set; }
        public string CashCode { get; set; }
        public string BankCode { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> ATM { get; set; }
        public Nullable<decimal> Visa { get; set; }
        public Nullable<decimal> Checks { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<decimal> PayedValue { get; set; }
        public Nullable<decimal> RemainderValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sa_POS_TrxDetails> sa_POS_TrxDetails { get; set; }
        public virtual tbl_Company tbl_Company { get; set; }
    }
}
