//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sa_POS_TrxDetails
    {
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
        public string TrxNo { get; set; }
        public string TrxType { get; set; }
        public string YearID { get; set; }
        public string PeriodID { get; set; }
        public decimal TrxLineNo { get; set; }
        public string Barcode { get; set; }
        public string ItemCode { get; set; }
        public string ItemService { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DiscountRatio { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public string ItemUnitCode { get; set; }
        public Nullable<decimal> UnitTransValue { get; set; }
        public string TrxDetailDescA { get; set; }
        public string TrxDetailDescE { get; set; }
        public Nullable<decimal> SourceDocLineNo { get; set; }
    
        public virtual sa_POS_TrxHeader sa_POS_TrxHeader { get; set; }
    }
}
