//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Company()
        {
            this.sa_POS_TrxHeader = new HashSet<sa_POS_TrxHeader>();
            this.tbl_Branch = new HashSet<tbl_Branch>();
            this.tbl_CustomerGroup = new HashSet<tbl_CustomerGroup>();
            this.tbl_Cutomers = new HashSet<tbl_Cutomers>();
            this.tbl_ItemCategory = new HashSet<tbl_ItemCategory>();
            this.tbl_ItemColor = new HashSet<tbl_ItemColor>();
            this.tbl_ItemDefinition = new HashSet<tbl_ItemDefinition>();
            this.tbl_ItemGroup = new HashSet<tbl_ItemGroup>();
            this.tbl_ItemSize = new HashSet<tbl_ItemSize>();
            this.tbl_ItemType = new HashSet<tbl_ItemType>();
            this.tbl_operators = new HashSet<tbl_operators>();
            this.tbl_VendorGroup = new HashSet<tbl_VendorGroup>();
            this.tbl_WareHouse = new HashSet<tbl_WareHouse>();
        }
    
        public string CompanyCode { get; set; }
        public string CompanyNameAr { get; set; }
        public string CompanyNameEn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sa_POS_TrxHeader> sa_POS_TrxHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Branch> tbl_Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerGroup> tbl_CustomerGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Cutomers> tbl_Cutomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemCategory> tbl_ItemCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemColor> tbl_ItemColor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemDefinition> tbl_ItemDefinition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemGroup> tbl_ItemGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemSize> tbl_ItemSize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemType> tbl_ItemType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_operators> tbl_operators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VendorGroup> tbl_VendorGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_WareHouse> tbl_WareHouse { get; set; }
    }
}
