//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ItemCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ItemCategory()
        {
            this.tbl_ItemDefinition = new HashSet<tbl_ItemDefinition>();
        }
    
        public string CompanyCode { get; set; }
        public string ItemCategoryCode { get; set; }
        public string ItemCategoryNameAr { get; set; }
        public string ItemCategoryNameEn { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        public virtual tbl_Company tbl_Company { get; set; }
        public virtual tbl_ItemCategory tbl_ItemCategory1 { get; set; }
        public virtual tbl_ItemCategory tbl_ItemCategory2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemDefinition> tbl_ItemDefinition { get; set; }
    }
}
