//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Vendors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Vendors()
        {
            this.tbl_PrTrxHeader = new HashSet<tbl_PrTrxHeader>();
        }
    
        public string CompanyCode { get; set; }
        public string VendoreCode { get; set; }
        public string VendoreGroupCode { get; set; }
        public string VendoreNameAr { get; set; }
        public string VendoreNameEn { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PrTrxHeader> tbl_PrTrxHeader { get; set; }
        public virtual tbl_VendorGroup tbl_VendorGroup { get; set; }
    }
}
