//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_POS_Definition
    {
        public string CompanyCode { get; set; }
        public string POSCode { get; set; }
        public string POSNameAr { get; set; }
        public string POSNameEn { get; set; }
        public string CashCode { get; set; }
        public string BankCode { get; set; }
        public Nullable<decimal> OpenBalance { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    }
}
