//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PrTrxDetails
    {
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
        public string TrxNo { get; set; }
        public string TrxType { get; set; }
        public string TraLineNo { get; set; }
        public string ItemService { get; set; }
        public string ItemCode { get; set; }
        public string ItemUnit { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public Nullable<decimal> UnitTransValue { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string BarCode { get; set; }
        public string WareHouseCode { get; set; }
        public Nullable<decimal> ItemCost { get; set; }
        public string VendoreCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDAte { get; set; }
        public string CreateBy { get; set; }
    
        public virtual tbl_PrTrxDetails tbl_PrTrxDetails1 { get; set; }
        public virtual tbl_PrTrxDetails tbl_PrTrxDetails2 { get; set; }
    }
}
