//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PrTrxHeader
    {
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
        public System.DateTime TrxDate { get; set; }
        public string TrxNo { get; set; }
        public string TrxStatus { get; set; }
        public string TrxType { get; set; }
        public string WareHouseCode { get; set; }
        public string VendoreCode { get; set; }
        public Nullable<decimal> TrxAmount { get; set; }
        public Nullable<decimal> TrxBalance { get; set; }
        public string IntRefrence { get; set; }
        public string TotalDiscount { get; set; }
        public string VendoreInvoiceNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string TrxDescAr { get; set; }
        public string TrxDescEn { get; set; }
    
        public virtual tbl_WareHouse tbl_WareHouse { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual tbl_Vendors tbl_Vendors { get; set; }
    }
}
