//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ItemRelatedUnits
    {
        public string CompanyCode { get; set; }
        public string ItemCode { get; set; }
        public string ItemService { get; set; }
        public string RelateUnitCode { get; set; }
    }
}
