//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Barcodes
    {
        public string CompanyCode { get; set; }
        public string ItemCode { get; set; }
        public string ItemService { get; set; }
        public string Barcode { get; set; }
        public string Status { get; set; }
        public string ItemUnit { get; set; }
        public Nullable<decimal> UnitTransValue { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ItemColorCode { get; set; }
        public string ItemSizeCode { get; set; }
        public Nullable<decimal> DiscountRatio { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        public virtual tbl_ItemDefinition tbl_ItemDefinition { get; set; }
    }
}
