USE [master]
GO

/****** Object:  Database [WMAPOS]    Script Date: 1/28/2017 8:44:32 PM ******/
CREATE DATABASE [WMAPOS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WMAPOS', FILENAME = N'E:\WMA\DB\WMAPOS.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WMAPOS_log', FILENAME = N'E:\WMA\DB\WMAPOS_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WMAPOS] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WMAPOS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WMAPOS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WMAPOS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WMAPOS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WMAPOS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WMAPOS] SET ARITHABORT OFF 
GO

ALTER DATABASE [WMAPOS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WMAPOS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WMAPOS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WMAPOS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WMAPOS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WMAPOS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WMAPOS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WMAPOS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WMAPOS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WMAPOS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WMAPOS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WMAPOS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WMAPOS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WMAPOS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WMAPOS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WMAPOS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WMAPOS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WMAPOS] SET RECOVERY FULL 
GO

ALTER DATABASE [WMAPOS] SET  MULTI_USER 
GO

ALTER DATABASE [WMAPOS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WMAPOS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WMAPOS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WMAPOS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WMAPOS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WMAPOS] SET  READ_WRITE 
GO


